application: listeregali
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /.*
  script: listanascita.application

- url: /edit
  script: listanascita.application
  login: admin

- url: /_ah/mail/.+
  script: forwardemail.py
  login: admin

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

inbound_services:
- mail

builtins:
- remote_api: on

